export const IS_AUTHENTICATING = 'IS_AUTHENTICATING'
export const UPDATE_AUTHORIZATION_STATE = 'UPDATE_AUTHORIZATION_STATE'
export const SIGNIN_ERROR = 'SIGNIN_ERROR'
export const SIGNUP_ERROR = 'SIGNUP_ERROR'
